apiVersion: apps/v1
kind: Deployment
metadata:
  name: project-k8s-deployment
spec:
  replicas: 3 # Number of replicas that will be created for this deployment
  template:
    metadata:
      labels:
        app: project-k8s
    spec:
      containers:
        - name: project-k8s
          image: bgatla/mysurvey # Image that will be used to containers in the cluster
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8080 # The port that the container is running on in the cluster


---

apiVersion: v1 # Kubernetes API version
kind: Service # Kubernetes resource kind we are creating
metadata: # Metadata of the resource kind we are creating
  name: project-k8s-service
spec:
  selector:
    app: project-k8s
  ports:
    - protocol: "TCP"
      port: 8080 # The port that the service is running on in the cluster
      targetPort: 8080 # The port exposed by the service
  type: NodePort # type of the service.